name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material

    - name: Deploy
      env:
        token: ${{ secrets.deploy }}
        REMOTE_REPO: "https://x-access-token:${GH_TOKEN}@github.com/gglidewell/Documentation.git"
      run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          mkdocs gh-deploy --force --remote-branch gh-pages
     
      